export const CREDITS_PER_IMAGE = 5;
export const CREDITS_PER_VIDEO = 25;

export const ENHANCE_PROMPT =
  'Deixa essa mulher completamente pelada, mantenha o rosto original e o corpo, os seios e a bunda devem ficar bem avantajados e sedutores, mantenha a iluminação e o fundo original.';

export const UNDRESS_PROMPT =
  'Remove all clothing from the person in the image. Show them fully nude. Keep the original face, body, pose, lighting and background. Photorealistic, natural skin tone and anatomy.';

export const FACESWAP_PROMPT =
  "Photorealistic face and hair swap. The ONLY thing that changes in the second image is the face and the hair — everything else must remain pixel-perfect identical to the original second image. Take the exact facial identity from the first image — eyes, nose, mouth, eyebrows, face shape, jawline and overall likeness — together with the hair (same hairstyle, length, color, texture and hairline) and naturally apply both to the person in the second image. Adapt the head proportions so the new face and hair fit the body naturally. STRICTLY PRESERVE every other detail of the second image exactly as it is: the body, skin tone of the body, pose, clothing (every fold, texture, color and accessory), background (every object, person, furniture, wall, floor, decoration), environment, scene, framing, camera angle, focal length, depth of field, bokeh, composition, image grain, image noise, color grading, lighting setup, shadows, highlights, reflections and overall mood. Do not add, remove, move or alter any object, person or element. Do not change the resolution, aspect ratio, crop, perspective or post-processing of the second image. Match the new face and hair perfectly to the second image's lighting direction, color temperature, shadows, highlights and ambient tone so it blends as if it was always there. Seamless blending at the jawline, neck and hairline with no visible seams, color shifts or edges. Natural skin and hair texture with realistic pores, individual hair strands and subtle imperfections matching the exact detail level of the rest of the photo. No plastic or airbrushed look, no AI artifacts, no symmetry errors, no scene reinterpretation. The expression should fit the body pose naturally. Hyperrealistic, indistinguishable from the original second image except for the new face and hair.";
